POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name": "Fernanda",
    "email": "Fernanda@gmail.com",
    "password":"xuxu123"

    
}

###

GET http://localhost:3003/user


###

POST http://localhost:3003/post/create
Content-Type: application/json

{
    
            "photo":"casa",
            "description":"casa amarela",
            "type": "normal",
            "authorId": "6cd75b33-633f-44e9-ad3d-8f88174012ae" 
            
}