CREATE TABLE Intro_Auth (
id VARCHAR (255) PRIMARY KEY,
name VARCHAR (255) NOT NULL,
nickname VARCHAR (255) NOT NULL,
email VARCHAR(255) NOT NULL,
password VARCHAR (255) NOT NULL
);

ALTER TABLE Intro_Auth ADD COLUMN role VARCHAR(255)